Feature/api
energinet-singularity/singupy pull request #9
Opened 2022-04-05 08:09 UTC by swedchef

This adds the 'api' module with two new classes.

The 'SQLRestAPI' class which can fire up a REST Api with SQL interaction with a single line of code.

The DataFrameAPI class which can serve Pandas DataFrame objects for SQL interaction, and also includes the prior mentioned class and thereby will allow SQL interaction with a pandas DataFrame via a REST api, again in a single line of code.

Category:

- [x] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [x] I have bumped all relevant version numbers
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my changes if this is needed
- [x] I have described my changes in the "description of your changes" field
- [x] I have tested this change on a running cluster 
- [x] I have created/corrected automated tests related to the changes, if possible/necessary
- [x] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-04-05 08:10 UTC, swedchef commented
Squash/Rebase to an atomic commit will be done upon agreeing on the included contents of the pull-request :)

2022-04-06 07:31 UTC, CodeWitten commented on README.md
>  ## Getting Started
Dependencies need to be added in dependencies section, or we could say they can be found under "install requires" in setup-py?

2022-04-06 07:43 UTC, CodeWitten commented on README.md
> +This class provides a REST API that accepts GET and POST requests - the latter for use with SQL Requests. The API can be linked to any two functions for GET and POST, where the latter will be sent an
I miss a more fulfilling description of what the class does and do not fully understand the sentence. I dot not have a specific suggestion to another formulation, so i am just complaining and asking you to fix it :)

2022-04-06 09:26 UTC, stigsberg requested changes
Your code fails your own pytest, this needs to be fixed. :)

2022-04-06 09:26 UTC, stigsberg commented on README.md
> +#### Parameters
I would prefer that all these parameters, extra options, etc are moved to the end of the documentation so the first thing you are presented to is the basic function and then go into all the extra you can do with the class. 

Peek my interest first then show me all the extra cool stuff.

2022-04-06 09:26 UTC, stigsberg commented on README.md
> +This is a custom thread object based on the standard threading.Thread object. It has the ability to shutdown the webserver.
This sentence can't have "Thread object." What are you trying to say?

2022-04-06 09:26 UTC, stigsberg commented on README.md
> +This class serves pandas DataFrames and can provide both metadata and respond to SQL queries. It includes the 'SQLRestAPI' class, and will by default run a webserver in a separate thread. SQL queries
Suggestion:
The served dataframe(s) can be changed **during** runtime and following queries will go to the new dataframes.

2022-04-06 09:26 UTC, stigsberg commented on README.md
> +This is the dataframe that will be served trough the API. It can be changed later. Default (or None) results in an empty dataframe being served (which cannot be queried).
Remove "It can be changed later. 
You have just stated this above.

2022-04-06 09:26 UTC, stigsberg commented on README.md
> +When accessing the items of the DataFrameAPI they return a dfconfig subclass object. This object has three properties, namely 'name' that will always be the same as the items name in the DataFrameAPI
Is "dfconfig" suppose to be: "dataframe config"?

2022-04-06 09:35 UTC, CodeWitten commented on README.md
> +curl -d '{"sql-query": "SELECT * FROM real_identity WHERE alterego = 'Batman';"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
I could not make curl work with my dataframe when using where statement. However using request worked. See attached photo and maybe just reach out for me to do debugging on it. Maybe i did stupid, maybe something need fixing.

![image](https://user-images.githubusercontent.com/94957526/161945150-e13126c9-1131-4399-bfe9-cc51ab535853.png)

2022-04-06 10:14 UTC, CodeWitten commented on singupy/api.py
> +                timeout = 15
I suggest we make the timeout as an attribute to the class with default value of 15 secounds.

2022-04-06 10:16 UTC, CodeWitten commented on singupy/api.py
> +            timeout = 15
I suggest we make the timeout as an attribute to the class with default value of 15 secounds. In general i prefer configuration parameters to be handled via parameters instead of directly specifying the number in the code.

2022-04-06 10:19 UTC, CodeWitten commented on singupy/api.py
> +    def __update_process(self):
add documentation to what the method does.

2022-04-06 10:21 UTC, CodeWitten commented on singupy/api.py
> +
Add a description of callable methods

2022-04-06 13:09 UTC, CodeWitten commented on singupy/api.py
> +        self.__port = port
Maybe google could help me, but now i ask you. Why do you use two underscores? As per my understanding 1 underscore is used to denote "internal" function or variabled. What are the reason for using double underscores?

2022-04-06 13:16 UTC, CodeWitten commented on singupy/api.py
> +    def start(self, wait_for_ready: bool = True) -> None:
consider changing it to something like "start_webservice", since later also "run" and "shutdown" methods are defined but they are not related to webservice as i understand.

2022-04-06 13:19 UTC, CodeWitten commented on singupy/api.py
> +        def __init__(self, host, port, app):
add short documentation to what the object does.

2022-04-06 13:24 UTC, CodeWitten commented on singupy/api.py
> +            log.info('starting server')
Maybe i lack knowled on the server threading, and therefore do not see the lines for this method to be self explanatory. However i would like a description of what happens with "ctx" property is used for and what push and server_forever does.

2022-04-06 13:24 UTC, CodeWitten commented on singupy/api.py
> +        def __init__(self, **kwargs):
add class documentation.

2022-04-06 20:09 UTC, swedchef commented on README.md
> +curl -d '{"sql-query": "SELECT * FROM real_identity WHERE alterego = 'Batman';"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
Incorrect formatting in my example - fixed it now. Sorry.

2022-04-06 20:13 UTC, swedchef commented on README.md
> +This is a custom thread object based on the standard threading.Thread object. It has the ability to shutdown the webserver.
I am uncertain how to make it more clear. I changed it a bit - but it is a 'Thread' object - an instance of a python class from the threading module.

2022-04-06 20:20 UTC, swedchef commented on singupy/api.py
> +
Actually i did this - but then found that was not best recommended. It would seem, that except in cases where you have a very large amount of non-necessary functions, you would just document the methods themselves (i.e. at the def start() method, not in the class docstring).

2022-04-06 20:23 UTC, swedchef commented on singupy/api.py
> +        self.__port = port
Single underscore is a nice "please do not use this" to other programmers, while double underscore uses "name mangling" (don't ask!) to actually hide the method (or what you are prepending it to). It's more private and should not be easily accesible from the outside.

2022-04-06 20:24 UTC, swedchef commented on singupy/api.py
> +                timeout = 15
Agreed - thought about it while i was making the code, but forgot. Will fix.

2022-04-07 07:12 UTC, CodeWitten commented on singupy/api.py
> +        self.__port = port
As i understand the documentation here: https://docs.python.org/3/tutorial/classes.html#private-variables, it is not more private. One underscore marks it as "not to be used outside class", but i acutally think it still can be used since python don't do private. However double underscores seems to only be relevant if you would like to avoid name clashing between classes and subclasses. I think in this code only one underscore should be used for attributes and methods.

2022-04-07 07:29 UTC, CodeWitten commented on singupy/api.py
> +        self[dbname] = dataframe
I have not seen this usage of self before and do not fully understand it. I understand it as a dictionary, but why not just create it as attribute instead of making it on "self". Please enlighten me on why it is clever (i assume it is)!

2022-04-07 07:36 UTC, CodeWitten commented on singupy/api.py
> +        dbdict = {name: self.__dfconfigs[name].dataframe for name in self.__dfconfigs
Why did you include this check. I get that it does not make sense to query an empty dataframe, but wouldn't it be better to handle it in response to query? or inform somehow that dataframe is empty upon assignment to the API.

2022-04-07 08:00 UTC, CodeWitten commented on tests/api_test.py
> +    global PORT, ENDPOINT
Is it necessary to use "global" when you only acess the variables? They are global since they are defined outside functions so should be acessible.

2022-04-07 08:05 UTC, CodeWitten commented on tests/api_test.py
> +    assert requests.get(f'http://localhost:{web.port}/{web.endpoint}').json() == json.dumps(GetDummy())
add comment to line.

2022-04-07 08:11 UTC, CodeWitten requested changes
Nerding at it's best. I really like your implementation and it is inspirational!

The readme is good and gives a brief well structured introduction to the api. 

The splitting up in two classes is a good design choice, since it makes it possible to use REST API to query other sources in the future. 

Your structure of the class is brilliant and very pythonic since you use decorators, special methods (__len__, ___iter__ and so on) to work with the object.

Nice use of threading - let's move more in that direction instead of script/loop-programming-style-ish.

The use of decorators for property setting is cool, didn't know they exist.

Really thorough testing. I am confident that the usecase of it is covered by the written tests.

Problems/questions:
- Some methods and functions need minor documentation to improve the readability. They are mentioned in the review. I know most of them are small, but for me just a oneline saying  “I start a threadish… by…” helps a lot. Let me know if you disagree on the level of documentation we do on these kinds of things. I know we must keep a balance to not overload our code with inline comments, but personally I found it hard having to google all the different libraries you use to understand the flow, comments would have helped at least understand the goal.

- I could not make curl request run, it is mentioned in one of my comments. Please contact me such that we can clarify if it is a bug or I am.

- Danish characters, are they handled properly? (contact me, I understood some issued maybe already was to you knowledge on this subject)

Keep coding like this! More please!

2022-04-07 08:26 UTC, swedchef commented on singupy/api.py
> +            log.info('starting server')
Removed - it was not necessary for our setup.

2022-04-07 08:29 UTC, swedchef commented on singupy/api.py
> +        dbdict = {name: self.__dfconfigs[name].dataframe for name in self.__dfconfigs
That was my initial intent - but when querying an empty dataframe pandaSQL makes a puking-sound and sends back something useless. By doing this i can control the return message and give a response that is a LITTLE better.

2022-04-07 10:12 UTC, swedchef commented on singupy/api.py
> +        self.__port = port
I agree - it was originally intended for another use, but it seems it is now used for making stuff private, and i prefer that right now. So .. For now, i would like to keep it like this. If we change opinion on how we want this in the future, it should be a quick swap-out.

2022-04-07 12:13 UTC, stigsberg approved these changes
LGTM

2022-04-07 12:22 UTC, CodeWitten approved these changes
Perfect. Merge the beauty!

2022-04-07 12:43 UTC, merged